// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/gallery": {
    params: {};
  };
  "/hotels": {
    params: {};
  };
  "/menu": {
    params: {};
  };
  "/rooms": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/contact" | "/gallery" | "/hotels" | "/menu" | "/rooms" | "/services" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./about/page.jsx": {
    id: "about/page";
    page: "/about";
  };
  "./contact/page.jsx": {
    id: "contact/page";
    page: "/contact";
  };
  "./gallery/page.jsx": {
    id: "gallery/page";
    page: "/gallery";
  };
  "./hotels/page.jsx": {
    id: "hotels/page";
    page: "/hotels";
  };
  "./menu/page.jsx": {
    id: "menu/page";
    page: "/menu";
  };
  "./rooms/page.jsx": {
    id: "rooms/page";
    page: "/rooms";
  };
  "./services/page.jsx": {
    id: "services/page";
    page: "/services";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "about/page": typeof import("./src/app/./about/page.jsx");
  "contact/page": typeof import("./src/app/./contact/page.jsx");
  "gallery/page": typeof import("./src/app/./gallery/page.jsx");
  "hotels/page": typeof import("./src/app/./hotels/page.jsx");
  "menu/page": typeof import("./src/app/./menu/page.jsx");
  "rooms/page": typeof import("./src/app/./rooms/page.jsx");
  "services/page": typeof import("./src/app/./services/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};